import { PartSpec, MatchResult } from '@/types/domain';

export function generateRFIEmail(
  part: PartSpec, 
  results: MatchResult[], 
  contactEmail: string = 'sourcing@tacto.com'
): string {
  const suppliers = results.map(r => r.supplier);
  const supplierList = suppliers.map(s => `• ${s.name} (${s.country})`).join('\n');
  
  const subject = `RFI: ${part.description} - ${part.part_number}`;
  
  const body = `Dear Supplier Partner,

We are issuing a Request for Information (RFI) for the following component:

PART SPECIFICATION:
- Part Number: ${part.part_number}
- Description: ${part.description}
- Material: ${part.material}
- Manufacturing Process: ${part.process}
- Annual Volume: ${part.annual_volume.toLocaleString()} units
${part.tolerance ? `- Tolerance: ${part.tolerance}` : ''}
${part.target_unit_price ? `- Target Unit Price: €${part.target_unit_price}` : ''}

INFORMATION REQUESTED:
1. Unit pricing for quantities: ${Math.floor(part.annual_volume * 0.1).toLocaleString()}, ${Math.floor(part.annual_volume * 0.5).toLocaleString()}, ${part.annual_volume.toLocaleString()} units/year
2. Lead time for prototypes and series production
3. Minimum order quantities
4. Available capacity and production slots
5. Quality certifications (ISO 9001, IATF 16949, etc.)
6. Sample availability and timeline

SUPPLIER SELECTION CRITERIA:
- EU-based manufacturing preferred
- IATF 16949 certification required for automotive applications
- Proven track record in similar components
- Competitive pricing with transparent cost breakdown
- Flexible capacity for volume fluctuations

NEXT STEPS:
1. Please confirm receipt and interest by [DATE + 3 days]
2. Submit preliminary information by [DATE + 1 week]
3. Selected suppliers will receive detailed RFQ package
4. Supplier audit and sample evaluation phase
5. Final supplier selection and contract negotiation

CONFIDENTIALITY:
This information is confidential and proprietary. Please sign and return the attached NDA before proceeding.

Selected suppliers for this RFI:
${supplierList}

For questions, please contact:
${contactEmail}

Best regards,
Tacto Sourcing Team

---
This email was generated by Tacto Sourcing Platform
`;

  // Create mailto link content
  const emlContent = `Subject: ${subject}
Content-Type: text/plain; charset=UTF-8

${body}`;

  return emlContent;
}

export function copyRFIToClipboard(content: string): Promise<void> {
  return navigator.clipboard.writeText(content);
}

export function downloadEMLFile(content: string, filename: string = 'rfi-email.eml'): void {
  const blob = new Blob([content], { type: 'message/rfc822' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}